# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DzAjpatimlG13cPBxRaSV8lIc4eAyUvl
"""

import sys
!{sys.executable} -m pip install streamlit

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="CLV Banking Dashboard",
    layout="wide"
)

st.title("📊 Customer Lifetime Value Dashboard")
st.subheader("Applied Business Analytics Project")

df = pd.read_csv("CLV_Final_Output.csv")


df["Gender_Label"] = df["Gender"].map({1: "Male", 0: "Female"})

def country_name(row):
    if row["Geography_Germany"] == 1:
        return "Germany"
    elif row["Geography_Spain"] == 1:
        return "Spain"
    else:
        return "France"

df["Country"] = df.apply(country_name, axis=1)

st.sidebar.header("Filter Customers")

segment = st.sidebar.multiselect(
    "Select Segment",
    options=df["Segment"].unique(),
    default=df["Segment"].unique()
)

country = st.sidebar.multiselect(
    "Select Country",
    options=df["Country"].unique(),
    default=df["Country"].unique()
)

gender = st.sidebar.multiselect(
    "Select Gender",
    options=df["Gender_Label"].unique(),
    default=df["Gender_Label"].unique()
)

filtered_df = df[
    (df["Segment"].isin(segment)) &
    (df["Country"].isin(country)) &
    (df["Gender_Label"].isin(gender))
]


col1, col2, col3, col4 = st.columns(4)

col1.metric("Customers", len(filtered_df))
col2.metric("Avg CLV", f"₹{round(filtered_df['CLV'].mean(),2)}")
col3.metric("Avg Balance", f"₹{round(filtered_df['Balance'].mean(),2)}")
col4.metric("Churn Rate", f"{round(filtered_df['Exited'].mean()*100,2)}%")

st.markdown("---")

st.subheader("Customer Segment Distribution")
st.bar_chart(filtered_df["Segment"].value_counts())

st.subheader("Average CLV by Country")
st.bar_chart(filtered_df.groupby("Country")["CLV"].mean())

st.subheader("Average CLV by Segment")
st.bar_chart(filtered_df.groupby("Segment")["CLV"].mean())

st.subheader("Top 10 High Value Customers")

top10 = filtered_df.sort_values("CLV", ascending=False).head(10)

st.dataframe(
    top10[
        [
            "Age",
            "Country",
            "Gender_Label",
            "Balance",
            "Tenure",
            "NumOfProducts",
            "CLV",
            "Segment"
        ]
    ]
)

st.subheader("Key Insights")

st.write("• Customers with higher balances create stronger lifetime value.")
st.write("• Active customers contribute more long-term profitability.")
st.write("• Multi-product customers are more valuable to the bank.")
st.write("• High CLV customers should be prioritized for retention.")
st.write("• Low-value customers can be targeted with cross-sell offers.")

st.markdown("---")
st.caption("Created for Applied Business Analytics Final Project")